name: Solar system Workflow
on:
    push:
        branches:
            - main
            - feature/*
    workflow_dispatch:

env:
    MONGO_URI: mongodb+srv://cluster0.s6hco5c.mongodb.net/?appName=Cluster0
    MONGO_USERNAME: roczyno
    MONGO_PASSWORD: Password1@

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                node-version: [18, 19, 20]
                operating-system: [ubuntu-latest, macos-latest]
                exclude:
                    - node-version: 18
                      operating-system: macos-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: archive test results
              uses: actions/upload-artifact@v6
              with:
                  name: mocha-test-results-${{ matrix.node-version }}-${{ matrix.operating-system }}
                  path: test-results.xml

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run tests with coverage
              continue-on-error: true
              run: npm run coverage

            - name: Archive coverage report
              uses: actions/upload-artifact@v6
              with:
                  name: coverage-report
                  path: coverage/
                  retention-days: 5
